name: ci
on:
  push:
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run tests (placeholder)
        run: echo "CI running! (Replace with real build/tests soon)"
