name: dast
on:
  workflow_dispatch:

permissions:
  contents: read
  # (no issues permission needed because we won't write issues)

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline scan (public test site)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: https://testphp.vulnweb.com   # reliable demo target
          allow_issue_writing: false            # <-- stop trying to create GitHub Issues
          fail_action: false                    # <-- don't fail the workflow
          cmd_options: "-a"                     # safe active/passive rules
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            report_json.json
