name: dast
on:
  workflow_dispatch:  # lets you click 'Run workflow' manually in Actions

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline scan (demo target)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: https://example.com
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
