name: dast
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: Run OWASP ZAP Baseline (Docker) — always succeed
        shell: bash
        run: |
          set +e
          docker run --rm -v "$PWD":/zap/wrk owasp/zap2docker-stable \
            zap-baseline.py -t https://testphp.vulnweb.com/ -a \
            -r zap.html -J zap.json
          echo "ZAP exit code was $?"
          # Ensure artifacts exist even if ZAP didn't write them
          [ -s zap.html ] || echo '<html><body><h3>No HTML from ZAP; see zap.json</h3></body></html>' > zap.html
          [ -s zap.json ] || echo '{"site":[],"alerts":[]}' > zap.json
          ls -lah zap.html zap.json

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap.html
            zap.json
