name: dast
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline scan (public test site)
        uses: zaproxy/action-baseline@v0.12.0
        continue-on-error: true          # <- never fail the run
        with:
          target: https://testphp.vulnweb.com
          allow_issue_writing: false     # don't try to open GitHub Issues
          fail_action: false             # extra safety
          cmd_options: "-a"              # safe active/passive rules

      - name: Upload reports
        if: always()                     # upload even if step had warnings
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            report_json.json
