name: dast
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Baseline in Docker (writes real reports)
        run: |
          # Run ZAP baseline inside the official Docker image.
          # The "|| true" means: don't fail the job if ZAP returns non-zero.
          docker run --rm \
            -v ${{ github.workspace }}:/zap/wrk \
            owasp/zap2docker-stable \
            zap-baseline.py -t https://testphp.vulnweb.com -a \
            -r zap.html -J zap.json || true

          echo "Files after scan:"
          ls -lah

          # Ensure BOTH files exist and are non-empty so the artifact step succeeds.
          [ -s zap.html ] || echo "<html><body><h3>No HTML from ZAP; see zap.json</h3></body></html>" > zap.html
          [ -s zap.json ] || echo '{"site":[],"alerts":[]}' > zap.json

      - name: Upload reports (both files)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap.html
            zap.json
