name: dast
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Baseline in Docker (writes real reports)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/zap/wrk \
            owasp/zap2docker-stable \
            zap-baseline.py -t https://testphp.vulnweb.com -a \
            -r zap.html -J zap.json || true
          echo "Files after scan:" && ls -lah

      - name: Upload reports (zip will contain BOTH files)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap.html
            zap.json
          if-no-files-found: error
